apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.50.10
  ports:
  - port: 1
- addresses:
  - ip: 192.168.50.11
  ports:
  - port: 1
- addresses:
  - ip: 192.168.50.12
  ports:
  - port: 1