apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-cluster
    path: gvol0
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs-cluster
    path: gvol0
    readOnly: false