apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv001
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  glusterfs:
    endpoints: glusterfs-cluster
    path: gvol0
    readOnly: false
